name: sevaexchange
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.2+115

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intro_slider:
    path: ./packages/intro_slider
  app_settings: ^4.0.0
  apple_sign_in: ^0.1.0
  arbify: ^0.0.9
  # async: null
  badges: ^1.1.1
  cached_network_image: ^2.0.0
  camera: 0.7.0+2
  cloud_firestore: ^0.12.5
  connectivity: ^0.4.8+6
  curved_navigation_bar: ^0.3.2
  dartz: ^0.9.2
  device_info: ^0.4.2+4
  emoji_picker: ^0.1.0
  file_picker: ^1.10.0
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.3+3
  firebase_dynamic_links: ^0.5.1
  firebase_messaging: ^6.0.16
  firebase_remote_config: ^0.3.1
  firebase_storage: ^3.1.6
  flurry: ^0.0.7
  flutter_downloader: ^1.4.4
  flutter_full_pdf_viewer: ^1.0.6
  flutter_google_places: ^0.2.3
  flutter_launcher_icons: 0.7.0
  flutter_linkify: ^3.1.3
  flutter_local_notifications: ^1.4.4+1
  flutter_phoenix: ^0.1.0
  # flutter_screenutil: ^1.1.0
  flutter_slidable: 0.4.9
  flutter_staggered_grid_view: ^0.3.2
  flutter_svg: ^0.18.0
  flutter_typeahead: ^1.8.1
  # geocode: ^0.1.3
  geocoding: ^1.0.5
  geoflutterfire: 2.0.3+5
  # geolocator: 6.1.5
  location: 
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.5.1
  # html: ^0.14.0+3
  http: ^0.12.1
  image_cropper: 1.0.0
  image_picker: ^0.6.7+1
  intl: ^0.16.1
  # keyboard_actions: ^3.2.0
  logger: ^0.7.0
  modal_progress_hud: ^0.1.3
  package_info: ^0.4.1
  path_provider: ^1.6.10
  pdf: ^1.10.0
  # permission_handler: ^5.0.1+1
  pin_code_text_field: ^1.6.0
  progress_dialog: ^1.2.3
  provider: ^4.3.3
  rxdart: ^0.22.0
  share: ^0.6.4+3
  share_extend: ^1.1.6
  shared_preferences: 0.5.4+1
  shimmer: ^1.1.1
  simple_animations: ^2.2.1
  # sliding_up_panel: ^1.0.2
  smooth_star_rating: 1.1.1
  store_redirect: ^1.0.2
  syncfusion_flutter_pdfviewer: ^18.4.49-beta
  timeago: 2.0.26
  # timezone: ^0.5.7
  url_launcher: ^5.4.11
  usage: ^3.4.1
  webview_flutter: ^0.3.22+1
  date_time_picker:
    path: ./packages/date_time_picker

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  pedantic: ^1.9.0
#  flutter_localizations:
#    sdk: flutter
arbify:
  url: http://localize.sevaexchange.com
  project_id: 9
  output_dir: lib/l10n

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/googlecal.png
    - lib/assets/images/outlookcal.png
    - lib/assets/images/ical.png
    - lib/assets/images/report_icon.jpeg
    - lib/assets/images/invoice_icon.jpeg
    - lib/assets/google-logo-png-open-2000.png
    - lib/assets/images/profile.png
    - lib/assets/images/seva-x-logo.png
    - lib/assets/images/close.png
    - lib/assets/images/group_icon.png
    - lib/assets/sevaX.png
    - images/seva-x-logo-white.png
    - lib/assets/images/g.png
    - lib/assets/images/approved.png
    - lib/assets/images/genericlogo.png
    - lib/assets/images/newsimage.png
    - lib/assets/images/noimagefound.png
    - lib/assets/images/add.png
    - lib/assets/images/add_.png
    - lib/assets/images/add__.png
    - lib/assets/images/apple-logo.png
    - lib/assets/images/info.png
    - lib/assets/images/help.png
    - lib/assets/images/signin_apple.png
    - lib/assets/images/pin.png
    - lib/assets/images/recycle-bin.png
    - lib/assets/images/image_02.png
    - lib/assets/images/search.png
    - lib/assets/images/csv.png
    - lib/assets/images/send.png
    - lib/assets/images/cv.png
    - lib/assets/images/apple-id-outline-yes_2x.png
    - lib/assets/images/request_offer_agreement_icon.png
    - null
    - images/
    - images/card_provider/

    #navigation bar Icons
    - images/icons/navigation_bar_icons/home_filled.png
    - images/icons/navigation_bar_icons/home_unfilled.png
    - images/icons/navigation_bar_icons/message_filled.png
    - images/icons/navigation_bar_icons/message_unfilled.png
    - images/icons/navigation_bar_icons/notifications_filled.png
    - images/icons/navigation_bar_icons/notifications_unfilled.png
    - images/icons/navigation_bar_icons/explore_filled.png
    - images/icons/navigation_bar_icons/explore_unfilled.png
    - images/icons/navigation_bar_icons/settings_filled.png
    - images/icons/navigation_bar_icons/settings_unfilled.png

    #icons
    - images/icons/create_message.png
    - images/icons/message.png
    - images/icons/remove_user.png
    - images/icons/camera.png
    - images/icons/cash_donation.png
    - images/icons/goods_donation.png
    - images/icons/verified.png
    - images/icons/recommended.png
    - images/icons/about.png
    - images/icons/projects.png
    - images/icons/members.png
    - images/icons/link.png
    - images/icons/multi_image.png

    - images/csv_example.png
    - images/icons/empty_widget.png
    # intro_screens
    - images/intro_screens/Broadcasting_feeds.png
    - images/intro_screens/Groups_and_Projects.png
    - images/intro_screens/Messaging_and_communication.png
    - images/intro_screens/Requests_and_Offers.png
    - images/intro_screens/What_is_a_timebank_and_how_can_people_find_and_join_one.png
    # card images

  fonts:
    # - family: Montserrat
    #   fonts:
    #     - asset: fonts/Montserrat-Regular.ttf
    #     - asset: fonts/Montserrat-Black.ttf
    #     - asset: fonts/Montserrat-BlackItalic.ttf
    #     - asset: fonts/Montserrat-Bold.ttf
    #     - asset: fonts/Montserrat-BoldItalic.ttf
    #     - asset: fonts/Montserrat-ExtraBold.ttf
    #     - asset: fonts/Montserrat-ExtraBoldItalic.ttf
    #     - asset: fonts/Montserrat-ExtraLight.ttf
    #     - asset: fonts/Montserrat-ExtraLightItalic.ttf
    #     - asset: fonts/Montserrat-Italic.ttf
    #     - asset: fonts/Montserrat-Light.ttf
    #     - asset: fonts/Montserrat-LightItalic.ttf
    #     - asset: fonts/Montserrat-Medium.ttf
    #     - asset: fonts/Montserrat-SemiBold.ttf
    #     - asset: fonts/Montserrat-SemiBoldItalic.ttf
    #     - asset: fonts/Montserrat-Thin.ttf
    #     - asset: fonts/Montserrat-ThinItalic.ttf
    - family: Europa
      fonts:
        - asset: fonts/EuropaBold.ttf
        - asset: fonts/EuropaBoldItalic.ttf
        - asset: fonts/EuropaLight.ttf
        - asset: fonts/EuropaLightItalic.ttf
        - asset: fonts/EuropaRegular.ttf
        - asset: fonts/EuropaRegularItalic.ttf
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: fonts/MavenPro-Bold.ttf
          weight: 700
